swagger: "2.0"
info:
  description: "This is G2i Node Test"
  version: "1.0.0"
  title: "Acronym"
  contact:
    email: "rexdev737@gmail.com"

tags:
- name: acronyms
  description: acronyms API
host: "localhost:3000"

paths:
# [GET] acronyms
  /acronyms:
    get:
      tags:
      - acronyms
      summary: Find All Acronyms
      parameters:
        - in: query
          name: from
          type: integer
        - in: query
          name: limit
          type: integer
        - in: query
          name: search
          type: string
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] acronyms
    post:
      tags:
      - acronyms
      summary: Add Acronym
      parameters:
      - name: body
        in: body
        description: acronym Data
        required: true
        schema:
          $ref: '#/definitions/acronyms'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] acronyms/name
  /acronyms/{name}:
    put:
      tags:
      - acronyms
      summary: Update Acronym By Name
      parameters:
      - in: path
        name: name
        description: acronym Name
        required: true
        type: string
      - name: body
        in: body
        description: acronym Data
        required: true
        schema:
          $ref: '#/definitions/acronyms'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] acronyms/name
    delete:
      tags:
      - acronyms
      summary: Delete Acronym By Name
      parameters:
      - name: name
        in: path
        description: acronym Name
        required: true
        type: string
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  acronyms:
    type: object
    required:
        - name
        - description
    properties:
      name:
        type: string
        description: acronym Name
      description:
        type: string
        description: acronym description

schemes:
 - http
